### PR TITLE
Added the bisection method

### PR DESCRIPTION
**Pull request by dieram3**

### CODE REVIEW

**Comment by jaguirresza** [comment]
great! :clap:

**Comment by jaguirresza** [comment]
`signbit` must be written as `std::signbit`to compile in `gcc`

**Comment by dieram3** [comment]
Fixed :) Now this pull request passes all checks.

**Comment by dieram3** [comment]
Also some docs have been clarified

**Comment by dieram3** [comment]
Merge?

**Comment by jaguirresza** [comment]
by the way some clue why the problem C fails ? :disappointed:

**Comment by dieram3** [comment]
There are rounding problems. I am working on that.

**Comment by dieram3** [comment]
There are serious rounding problems, f(1000) should return 0 in the third test case.
When points are scaled by 2^20 using double returns 12816.7 and using long double returns 8.74445. Some techniques can be used to prevent these errors like this one https://en.wikipedia.org/wiki/Kahan_summation_algorithm but it still seems not working.

**Pull request merged**
